server:
  port: 9192
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Student_MIS
    username: jon
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      'hibernate.format_sql': true
 
 
